### Задача

1. Задан двухмерный массив ar1 размерности (10, 10), состоящий из случайных целых чисел в пределах от 0 до 15. Вычислить разность s_odd - s_even, где s_odd - сумма элементов, стоящих на позиции (x, y), где (x + y) является нечетным числом; s_even - сумма элементов, стоящих на позиции (x, y), где (x + y) является четным числом.
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек


In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=0, high=16, size=(10, 10))
arr

array([[10,  1,  7,  6, 11,  0,  4, 13, 12,  4],
       [ 2, 13,  7,  3,  0,  2,  3,  1,  6, 11],
       [12,  4, 15,  5,  8,  2, 15,  4, 13, 11],
       [ 9, 13,  2,  0,  7,  8,  4,  0,  0,  7],
       [ 8, 10, 14, 14,  4,  7, 15,  4,  8,  8],
       [ 8, 15,  2,  5,  9,  3, 14,  2,  7, 15],
       [ 0,  8, 14,  2, 15,  1,  0,  2, 14, 11],
       [ 6,  6,  3,  6,  2,  4,  5,  3, 12,  0],
       [ 8, 11,  8, 12, 11, 12,  7,  8,  1,  6],
       [ 2, 13, 14, 14, 14, 10,  7,  6, 15, 13]])

In [3]:
arr[::2]

array([[10,  1,  7,  6, 11,  0,  4, 13, 12,  4],
       [12,  4, 15,  5,  8,  2, 15,  4, 13, 11],
       [ 8, 10, 14, 14,  4,  7, 15,  4,  8,  8],
       [ 0,  8, 14,  2, 15,  1,  0,  2, 14, 11],
       [ 8, 11,  8, 12, 11, 12,  7,  8,  1,  6]])

In [4]:
arr[1::2]

array([[ 2, 13,  7,  3,  0,  2,  3,  1,  6, 11],
       [ 9, 13,  2,  0,  7,  8,  4,  0,  0,  7],
       [ 8, 15,  2,  5,  9,  3, 14,  2,  7, 15],
       [ 6,  6,  3,  6,  2,  4,  5,  3, 12,  0],
       [ 2, 13, 14, 14, 14, 10,  7,  6, 15, 13]])

In [5]:
s_even = np.sum([arr[::2,::2], arr[1::2,1::2]])
s_even

407

In [6]:
s_odd = np.sum([arr[1::2,::2], arr[::2,1::2]])
s_odd

326

In [7]:
s_odd - s_even

-81

### Проверка решения

In [8]:
s_odd_check = 0
s_even_check = 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if (np.sum([i,j])%2 == 1):
            s_odd_check+=arr[i][j]
        else:
            s_even_check+=arr[i][j]

In [9]:
assert s_odd_check == s_odd

In [10]:
assert s_even_check == s_even_check