### Задача 1

Задан двухмерный массив ar1 размерности (10, 10), состоящий из случайных целых чисел в пределах от 0 до 15. Вычислить разность s_odd - s_even, где s_odd - сумма элементов, стоящих на позиции (x, y), где (x + y) является нечетным числом; s_even - сумма элементов, стоящих на позиции (x, y), где (x + y) является четным числом.
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек


In [1]:
import numpy as np

In [2]:
#Создаем массив 10x10 с числами от 0 до 15
ar1 = np.random.randint(low=0, high=16, size=(10, 10))
ar1

array([[ 9, 14, 11, 14,  5,  1, 10, 14, 12,  2],
       [14,  2, 12,  2,  3,  6,  3,  8,  3,  5],
       [ 0, 13,  1,  4, 15, 11, 14, 13,  7, 14],
       [14, 14,  9, 15,  6,  9,  3, 10, 15, 10],
       [ 5,  0,  3,  9,  8,  5,  6,  0,  7,  3],
       [13, 10, 15, 11,  7,  1, 15, 11,  2,  7],
       [ 4, 13,  7,  4,  6,  1, 11, 14,  4,  7],
       [ 7,  1,  8,  2,  5,  5,  8, 11, 15,  8],
       [14,  1,  0,  9, 11, 13, 15, 10, 11,  3],
       [11,  5, 10, 13,  8, 14,  1, 11,  9,  4]])

In [3]:
ar1[::2]

array([[ 9, 14, 11, 14,  5,  1, 10, 14, 12,  2],
       [ 0, 13,  1,  4, 15, 11, 14, 13,  7, 14],
       [ 5,  0,  3,  9,  8,  5,  6,  0,  7,  3],
       [ 4, 13,  7,  4,  6,  1, 11, 14,  4,  7],
       [14,  1,  0,  9, 11, 13, 15, 10, 11,  3]])

In [4]:
ar1[1::2]

array([[14,  2, 12,  2,  3,  6,  3,  8,  3,  5],
       [14, 14,  9, 15,  6,  9,  3, 10, 15, 10],
       [13, 10, 15, 11,  7,  1, 15, 11,  2,  7],
       [ 7,  1,  8,  2,  5,  5,  8, 11, 15,  8],
       [11,  5, 10, 13,  8, 14,  1, 11,  9,  4]])

In [5]:
#s_even - сумма элементов, стоящих на позиции (x, y), где (x + y) является четным числом
s_even = np.sum([ar1[::2,::2], ar1[1::2,1::2]]) #четн
s_even

391

In [6]:
#s_odd - сумма элементов, стоящих на позиции (x, y), где (x + y) является нечетным числом
s_odd = np.sum([ar1[1::2,::2], ar1[::2,1::2]]) #нечетн
s_odd

408

In [7]:
s_odd - s_even

17

### Проверка решения

In [8]:
s_odd_check = 0
s_even_check = 0

for i in range(ar1.shape[0]):
    for j in range(ar1.shape[1]):
        if (np.sum([i,j]) % 2 == 1):
            s_odd_check += ar1[i][j]
        else:
            s_even_check += ar1[i][j]

In [9]:
assert s_odd_check == s_odd

In [10]:
assert s_even_check == s_even_check